url: 'http://www.hd.ai'
host: hd.ai
siteType: NexusPHP
asSource: true
asTarget: true
uploadPath: /Torrents.upload
seedDomSelector: '#top+table>tbody>tr:nth-child(3)'
search: 
  path: /Torrents.index
  imdbOptionKey: '9'
  nameOptionKey: '1'
  params:
    name: '{name}'
    search_area: '{optionKey}'
    imdb: '{imdb}'
name:
  selector: '#name'
subtitle:
  selector: 'input[name="small_descr"]'
description:
  selector: '#descr'
poster: 'input[name="poster"]'
imdb:
  selector: 'input[name="url"][type="text"]'
mediaInfo:
  selector: 'textarea[name="nfo"]'
screenshots:
  selector: 'textarea[name="screenshot"]'
tags: 
  chineseAudio: 'input[type="checkbox"][name="tag[cn]"]'
  chineseSubtitle: 'input[type="checkbox"][name="tag[zz]"]'
category:
  selector: 'select[name="type"]'
  map:
    movie: '1'
    tv: '2'
    tvPack: '2'
    documentary: '4'
    concert: '6'
    sport: '7'
    cartoon: '5'
    variety: '3'
videoCodec:
  selector: 'select[name="codec_sel"]'
  map:
    h264: '2'
    hevc: '1'
    x264: '2'
    x265: '1'
    h265: '1'
    mpeg2: '5'
    mpeg4: '2'
    vc1: '3'
    xvid: '4'
    dvd: '5'
audioCodec:
  selector: 'select[name="audiocodec_sel"]'
  map:
    aac: '10'
    ac3: '11'
    dd: '11'
    dd+: '11'
    flac: '7'
    dts: '5'
    truehd: '4'
    lpcm: '6'
    dtshdma: '2'
    atmos: '3'
    dtsx: '1'
videoType:
  selector: 'select[name="medium_sel"]'
  map:
    uhdbluray: '1'
    bluray: '2'
    remux: '3'
    encode: '5'
    web: '4'
    hdtv: '6'
    dvd: '7'
    dvdrip: '10'
    other: '0'
resolution:
  selector: 'select[name="standard_sel"]'
  map:
    4320p: '1'
    2160p: '2'
    1080p: '3'
    1080i: '4'
    720p: '5'
    576p: '6'
    480p: '6'
area:
  selector: 'select[name="source_sel"]'
  map:
    CN: '1'
    US: '2'
    EU: '2'
    HK: '3'
    TW: '3'
    JP: '4'
    KR: '5'
    OT: '6'
team: 
  selector: 'select[name="team_sel"]'
  map:
    other: '1'
    ao: '20'
    beitai: '18'
    beyondhd: '19'
    beast: '23'
    chd: '2'
    chdbits: '3'
    cmct: '4'
    frds: '5'
    fltth: '17'
    hdai: '6'
    hdchina: '7'
    hdhome: '8'
    hdsky: '9'
    lemonhd: '28'
    leaguehd: '29'
    mteam: '10'
    nypt: '24'
    ngb: '26'
    ourtv: '11'
    ourbits: '12'
    pter: '13'
    pthome: '14'
    putao: '22'
    strife: '21'
    tjupt: '15'
    ttg: '16'
    tlf: '30'
    u2: '31'
    wiki: '25'